### ISSUE TITLE
WAIL should probably terminate Heritrix/Tomcat on close

### ISSUE THREAD

**Issue by shawnmjones** [N0taN3rd/wail#42]
I am using WAIL on OS X 10.11.6.

When I choose "wail->Quit wail" in the application menu, the GUI goes away, but Tomcat/Heritrix is still running:

```
  502   898     1   0 10:50PM ??         0:27.34 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Dheritrix.home=/Applications/wail.app/Contents/Resources/app/bundledApps/heritrix-3.3.0 -Djava.protocol.handler.pkgs=org.archive.net -Dheritrix.out=/Applications/wail.app/Contents/Resources/app/bundledApps/heritrix-3.3.0/heritrix_out.log -Xmx256m org.archive.crawler.Heritrix -a lorem:ipsum
  502   913     1   0 10:50PM ??         0:11.41 /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java -Djava.util.logging.config.file=/Applications/wail.app/Contents/Resources/app/bundledApps/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.endorsed.dirs=/Applications/wail.app/Contents/Resources/app/bundledApps/tomcat/endorsed -classpath /Applications/wail.app/Contents/Resources/app/bundledApps/tomcat/bin/bootstrap.jar:/Applications/wail.app/Contents/Resources/app/bundledApps/tomcat/bin/tomcat-juli.jar -Dcatalina.base=/Applications/wail.app/Contents/Resources/app/bundledApps/tomcat -Dcatalina.home=/Applications/wail.app/Contents/Resources/app/bundledApps/tomcat -Djava.io.tmpdir=/Applications/wail.app/Contents/Resources/app/bundledApps/tomcat/temp org.apache.catalina.startup.Bootstrap start
```

Is this intentional?

I know I am a special use case because I am also running other software that might want to use the same ports, but others may feel that it is misleading to keep these processes running after closing the application.

**Comment by N0taN3rd** [comment]
@shawnmjones currently yes this is intentional ...... but it is planned to not keep them running after WAIL has been shut down. Lacked the ticket item until now 😄 

To address this use case I have been considering some options: dialogue on quit to ask if they should be shut down, configurable options as to how WAIL should act in this case, and or some combination of the two.

Is there a manner in which you would feel most comfortable with in handling this?

**Comment by shawnmjones** [comment]
I imagine that some users may actually want Heritrix to keep running after the GUI is shut down. In my case, it would be nice to just have some kind of checkbox in the WAIL configuration GUI that I could check and thus avoid having to hunt down and kill the process. Something like this?

 ▢ Shut down all processes on exit

For now, you could leave the default as unchecked - i.e., don't kill the processes on shutdown - and then change the default later, but leave the option in place for those who may want to keep it running?

**Comment by machawk1** [comment]
@N0taN3rd I like the idea of showing a dialog when the user quits asking if they also want Heritrix, Wayback, etc. shut down as well. You might even first check if there is a Heritrix crawl that is running and if not, change the default value of the Shut Down Heritrix box. 

The "Keep Running" aspect is more applicable to Heritrix, since crawl jobs take a long time, than Wayback; i.e., I foresee users as thinking it intuitive for the crawl job to continue once WAIL is closed whereas they would expect to have to open the WAIL app for OpenWayback to be accessible.

**Comment by shawnmjones** [comment]
👍

**Comment by N0taN3rd** [comment]
@machawk1 Another option I have thought would be to heritrix on demand. Do not start it unless a crawl is initiated and shut it down after some period of no utilization time.  This might be to aggressive when it comes policing the up time of heritrix which would lead too complaints about having to constantly restart heritrix?

**Comment by machawk1** [comment]
I think it's better to keep Heritrix running by default so long as WAIL is running unless the user explicitly says to kill Heritrix. There is likely latency and overhead in starting and killing Heritrix, so keep it running.
