### ISSUE TITLE
Don't show table for collection when no seeds exist

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/wail#65]
Prior to adding any seeds, selecting the collection shows a table just with table headers and no data (see attached). This could potentially confusing to the user and is neither helpful nor provides guidance on what the user should do.

Let's provide something in the UI to guide the user into adding seeds **instead** of showing a blank table.

Also, selecting the SHOW ARCHIVE CONFIGURATIONS button (though it's not entirely clear this is actionable solely from it being bold and vertical inline with the table headers) provides a notification saying, "Add Seeds to default In Order To View Their Archive Config". We should make this clickable (i.e., w/ corresponding verbiage in the notification), to 1. Make the notification more useful than simply informative 2. Remove a few steps between the user remedying their current situation of having no seeds in the collection.

![screen shot 2017-01-24 at 1 19 52 pm](https://cloud.githubusercontent.com/assets/2514780/22260649/f2d53a96-e237-11e6-9e88-30e81614d6b6.png)

**Comment by N0taN3rd** [comment]
@machawk1  would making the show archive configurations button raised be any better, simply in for ease of identification of clickable? 
Neglecting the button in the notification displayed when clicking the view archive configuration and no seeds was an oversight on my part.

Instead of the blank screen a simple message: click the green/fab/plus button  to add to the collection or message: no seeds would you like to add <add button beside message> 

A notification dispatched by default when viewing this screen + no seeds that states the no seeds plus clickable element for adding is another option.
My intuition at the time was the fab + blank contents would be indicative of users needing to click it.

**Comment by machawk1** [comment]
I think there are two issues with the SHOW ARCHIVE CONFIGURATION button design wise inclusive of it being vertically aligned with the table headers and not itself a header and the subtlety of boldness in an attempt to distinguish it as a button or clickable item. Are the table headers usually clickable? Even if so, for say, the sake of sorting, the action does not correspond to the button. Changing the placement of the button might help but also make it more button-esque in design. I don't know how that matches up with the Material Design paradigm you've implemented, so I'll defer to you for the best way to accomplish this.

Some direction as to what the mysterious "+" button would be welcomed. That was originally one of my reservations of the buttons not being clear as to what they accomplish; "+" what?

A blank UI says to me, "Oops, the dev forget to do this part", not, "Well, there's only one thing to do and ALL THIS WHITESPACE". ;)

**Comment by weiglemc** [comment]
I think that the Archive Configuration should just be another column in the table rather than a separate button.  If a seed has been archived with multiple archive configurations (once with page only and once with page + same domain), then we just list them both in that cell.

**Comment by N0taN3rd** [comment]
closing per 1.2.0-beta2
