### ISSUE TITLE
More Twitter suggestions

### ISSUE THREAD

**Issue by weiglemc** [N0taN3rd/wail#72]
Allow users to include @ in the username or not.

If possible, show the given user's timeline (as a verification/check) before user presses the 'Start' button. (Maybe this should already be there -- the title of the box is "A User's Timeline")

Why is there a limit for only 50 minutes of monitoring?

With the wording of "A User's Timeline", I was expecting that the timeline would be archived rather than individual tweets.  The result is that if the user tweets a lot, each tweet becomes a new seed rather than the timeline being a single seed and collecting additional mementos.

_(Let me know if you want me to split these out into separate issues.)_

**Comment by N0taN3rd** [comment]
@weiglemc 

The "50 minute" limit was an unintentional side effect of the sizing used. 
If you type another value the others will be displayed autocomplete style but will be tweaking size.

The wording does imply the whole timeline rather than scanning it for tweets.
Switching over to grabbing the timeline itself per the issue would be appropriate.
